openslate/compose-flow

README.md
Added some stuff that we talked about on slack.
=> Added env docs.

Pipfile, Pipfile.lock, src/compose_flow/commands/compose_flow.py, src/compose_flow/commands/subcommands/base.py, src/compose_flow/commands/subcommands/compose.py, src/compose_flow/commands/subcommands/config_base.py, src/compose_flow/commands/subcommands/deploy.py, src/compose_flow/commands/subcommands/env.py, src/compose_flow/commands/subcommands/profile.py, src/compose_flow/commands/subcommands/publish.py, src/compose_flow/commands/subcommands/remote.py, src/compose_flow/commands/subcommands/service.py, src/compose_flow/commands/subcommands/task.py, src/compose_flow/utils.py, src/tests/test_env.py, src/tests/test_publish.py
The current version we are using is from my fork's master branch.
=> Get openslate master up to date with rca/master

.dockerignore, .gitignore, Dockerfile, Jenkinsfile, Pipfile, Pipfile.lock, compose/compose-flow.yml, compose/docker-compose.publish.yml, compose/docker-compose.yml, files/root/.pypirc, files/usr/local/bin/entrypoint.sh, pylama.ini, scripts/lock.sh, src/compose_flow/commands/subcommands/compose.py, src/compose_flow/commands/subcommands/config_base.py, src/compose_flow/commands/subcommands/env.py, src/compose_flow/commands/subcommands/kompose.py, src/compose_flow/commands/workflow.py, src/compose_flow/shell.py, src/compose_flow/utils.py, src/tests/test_base.py
Resolves openslate/openslate#1732
=> Add Jenkinsfile with linting, testing, and publishing

src/compose_flow/commands/subcommands/deploy.py, src/compose_flow/commands/subcommands/kube_mixin.py, src/compose_flow/shell.py
Contributes to openslate/openslate#1728
=> Enhance Kubernetes Support

Pipfile, Pipfile.lock, src/compose_flow/commands/subcommands/swarm.py, src/compose_flow/commands/workflow.py, src/compose_flow/docker.py, src/compose_flow/errors.py, src/tests/test_docker.py
Initial swarm command to inspect important service attributes that affect stability.
=> Add swarm command

.dockerignore, Dockerfile, Pipfile, Pipfile.lock, setup.py
Now we only have a single listing of dependencies, plus we can call `compose-flow` from inside the container built by this project
Contributes to openslate/openslate#1779
=> Consolidate Pipfile and setup.py to allow running compose-flow inside container

.dockerignore
Tried to save build time by ignoring some stuff so cache wouldn't invalidate but that broke publishing
=> Remove stuff from dockerignore to fix publishing

Dockerfile, src/compose_flow/commands/subcommands/kube_mixin.py
In order to actually run `compose-flow` commands inside the container we need to have the Docker client installed
=> Add Docker client to image

Dockerfile
Previous PR installed outdated version of Docker client without `config` command
=> Update to proper version of docker client

Pipfile.lock, setup.py
=> Add docker-compose to setup.py requirements

Dockerfile, MANIFEST.in, Pipfile, Pipfile.lock, setup.py, src/compose_flow/commands/subcommands/deploy.py
Contributes to openslate/openslate#1728
Reverses setup.py and Pipfile relationship for better Docker build caching
=> Add k8s tooling to Docker image and improve build caching

compose/compose-flow.yml, compose/docker-compose.mount.yml, pylama.ini, src/compose_flow/commands/subcommands/deploy.py, src/compose_flow/commands/subcommands/kube_mixin.py, src/compose_flow/commands/subcommands/rancher.py, src/compose_flow/errors.py, src/compose_flow/kube/checks.py, src/compose_flow/kube/mixins.py, src/tests/files/answers/multidoc-answers.yaml, src/tests/files/answers/no-limits-answers.yaml, src/tests/files/answers/no-requests-answers.yaml, src/tests/files/manifests/external-zalando-ingress.yaml, src/tests/files/manifests/internal-zalando-ingress.yaml, src/tests/files/manifests/invalid-ingress-multidoc.yaml, src/tests/files/manifests/invalid-zalando-ingress.yaml, src/tests/files/manifests/nginx-ingress.yaml, src/tests/files/manifests/no-limits-deployment.yaml, src/tests/files/manifests/no-resources-job.yaml, src/tests/test_kube_checks.py
Resolves openslate/openslate#1778
=> Kubernetes YAML validation

Dockerfile, src/compose_flow/kube/mixins.py
Trying to deal with repercussions of running as non-root user and a weird issue that came up after upgrading `sh`
=> Change src dir perms and catch more sh errors

Jenkinsfile, compose/compose-flow.yml
Finally close to having the publish logic working inside the inner container!
=> Fix up publish logic

src/compose_flow/commands/subcommands/task.py, src/tests/test_task.py
Resolves openslate/openslate#1893
=> Tasks should update version vars

src/compose_flow/commands/subcommands/env.py, src/compose_flow/commands/workflow.py, src/compose_flow/settings.py, src/tests/test_publish.py, src/tests/test_workflow.py
=> Allow DOCKER_IMAGE_PREFIX to be set in config file

src/compose_flow/commands/subcommands/env.py, src/compose_flow/environment/backends/base_backend.py, src/compose_flow/environment/backends/kube_backend.py, src/compose_flow/environment/backends/local_backend.py, src/compose_flow/environment/backends/rancher_backend.py, src/compose_flow/environment/backends/swarm_backend.py, src/compose_flow/errors.py, src/compose_flow/kube/mixins.py, src/tests/test_backends.py
Resolves openslate/openslate#1848
=> Add support for Kubernetes Secrets as a Backend

src/compose_flow/commands/subcommands/env.py, src/tests/test_env.py
Eases the transition to using Rancher as a backend for compose-flow from Jenkins
Resolves openslate/openslate#2065
=> Add logic to support per-project configuration of the backend

Dockerfile, README.md, src/compose_flow/kube/mixins.py
Resolves openslate/openslate#2120
=> Add logic to read Rancher defaults from global app config

compose/compose-flow.yml
Contributes to openslate/openslate#2052
=> Switch compose-flow remote backends to Rancher

Jenkinsfile, Pipfile.lock, compose/compose-flow.yml, src/compose_flow/environment/backends/swarm_backend.py, src/compose_flow/kube/mixins.py, src/tests/test_env.py, src/tests/test_remote.py
Contributes to openslate/openslate#2288
=> Ensure Jenkins jobs clean up after themselves

docs/advanced.md, src/compose_flow/commands/subcommands/deploy.py, src/compose_flow/errors.py, src/compose_flow/kube/mixins.py, src/tests/test_deploy.py
Resolves openslate/openslate#2051
Tested locally with an example project, seems to work as intended
=> Add support for Rancher namespace creation during deployment

Pipfile.lock
See this PR in twine for details: https://github.com/pypa/twine/pull/447
=> Fixes build issues refrencing pyopenssl.

src/compose_flow/commands/subcommands/__init__.py, src/compose_flow/commands/subcommands/base.py, src/compose_flow/commands/subcommands/build.py, src/compose_flow/commands/subcommands/publish.py
Resolves openslate/openslate#1877
=> Refactor build and publish subcommand to use common base class

Dockerfile
Upgrades Rancher and Docker clients to pick up bug fixes and enhancements
=> Upgrade CLI tools

docs/advanced.md, src/compose_flow/kube/mixins.py
Easier to deploy complex configuration and supports multi-line strings
=> Add support for nested values

src/compose_flow/commands/subcommands/helm.py, src/compose_flow/commands/subcommands/kubectl.py, src/compose_flow/commands/subcommands/passthrough_base.py
Found some annoying minor issues with the k8s subcommands
=> Fix up some minor issues with k8s subcommands

Pipfile.lock
In order to ensure that the versions are compatible when running in jenkins, relock the file in a container.
=> Relock pipfile in docker container

Pipfile.lock
Otherwise, the container will have issues if it's locked on a mac.
=> Lock the pipfile in the container

Dockerfile, scripts/lock.sh, src/compose_flow/kube/checks.py, src/compose_flow/kube/mixins.py
Contributes to https://openslate.myjetbrains.com/youtrack/issue/OS-2997
=> Upgrade Rancher and Docker CLIs

Dockerfile, src/compose_flow/kube/mixins.py
Contributes to https://openslate.myjetbrains.com/youtrack/issue/OS-3905
=> Upgrade to Helm 3 CLI

Pipfile, Pipfile.lock
=> Relock Pipfile to pick up security updates

Dockerfile
We're off of k8s 1.15 so we should upgrade kubectl to 1.17
=> Upgrade kubectl to 1.17.17
