openslate/compose-flow

src/compose_flow/commands/subcommands/compose.py, src/compose_flow/commands/subcommands/publish.py, src/compose_flow/entrypoints.py, src/compose_flow/settings.py
When a compose setup is building multiple images, support being able to publish them all.
=> Infer which images need to be pushed

src/compose_flow/commands/subcommands/task.py
This is a pretty critical issue that needs to be merged to move forward with `3.x.x`
Without this fix most Jenkins pipelines that use `cf` would break
=> HOTFIX: Add back compose as a profile subcommand for tasks so YAML gets rendered

Jenkinsfile
Avoids missing credentials by using standard image publish function
=> Switch to standard function for Jenkins Docker image publish

src/compose_flow/commands/subcommands/env.py, src/compose_flow/utils.py, src/tests/test_env.py, src/tests/test_publish.py
Use the same convention for building the image name between publishing and
deploying.  The previous revision would dynamically geneate the image name when
publishing, but only update the tag while deploying.
This patch dynamically geneates the name during publishing as well such that it
matches with publishing.
The reason the image name is dynamically generated during publishing is that
there is no need to be connected to a remote machine or access the config for
building and publishing.
=> Make some tweaks to be consistent with docker image name

src/compose_flow/commands/subcommands/deploy.py
We had started requiring a profile for Rancher to get access to `DOCKER_SERVICE` and such, but on second thought we should use a more k8s native solution like `kustomize` https://github.com/kubernetes-sigs/kustomize
=> Don't require a profile to be defined for Rancher deployments

.gitignore
Since we run `python setup.py install` inside the container we now have to ignore the `build` and `dist` directories to avoid `tag-version` failing on unclean working directory
=> HOTFIX: ignore artifact directories to avoid publish failure

src/compose_flow/commands/subcommands/build.py
It gets old having to run `compose-flow compose build --pull` just to build the project's images
This allows you to just run `compose-flow build`
Resolves openslate/openslate#1786
Lifted pretty much line-for-line from `publish.py`
=> Add simple build subcommand

Jenkinsfile, src/compose_flow/commands/subcommands/compose.py, src/compose_flow/commands/subcommands/env.py, src/compose_flow/commands/workflow.py, src/tests/test_workflow.py
Trying to resolve the inconsistencies with how compose services get named
Also adds temporary Jenkinsfile logic to address issues with `task` subcommand
Contributes to openslate/openslate#1893
=> Rework config name vs project name logic

src/compose_flow/commands/subcommands/env.py
After changing the `compose` subcommand to use `project_name` several bugs emerged, likely caused by these lingering references to `workflow.args.project_name` which now may be null
=> Fix broken refs to project_name arg

src/compose_flow/utils.py
Need to get this in quick since it's causing problems with k8s deployments that use Secrets
=> Fix base 64 encoding filter to return proper string

README.md, src/compose_flow/commands/subcommands/remote.py, src/compose_flow/commands/subcommands/service.py, src/compose_flow/commands/workflow.py, src/compose_flow/settings.py, src/tests/test_remote.py
Removes the need to set $CF_REMOTE_USER and infers the remote username from the ssh configuration in the application config.
=> Get remote user from appconfig

src/compose_flow/commands/subcommands/pod.py, src/compose_flow/errors.py, src/tests/test_pod.py
- switch rancher context instead of kube context
- use workflow project_name as namespace param
- improve error handling when a pod cannot be found
- allow escape hatch namespace override with `--namespace`
=> Fixup the pod exec command.

Jenkinsfile, src/compose_flow/commands/subcommands/env.py, src/tests/test_env.py
~Need to test this locally~
Tested this locally, it seems to work as expected: when a variable is not defined it can be edited as `runtime://` but it throws an error if you try to run `compose` or `deploy` without defining a variable
Resolves openslate/openslate#2433
=> Add logic to allow editing of runtime variables without defining them

src/compose_flow/kube/mixins.py
Spent too much time trying to figure out an error on the cli, which was due to the cf env not being defined.  The namespace would have helped and given me better direction to fix the problem.
=> Add namespace to NoSuchConfig error

src/compose_flow/commands/subcommands/deploy.py, src/compose_flow/kube/mixins.py, src/tests/test_deploy.py
Allows users to leverage `kubectl`'s native support for loading manifests from remote URLs
=> Add support for URL manifest paths

src/compose_flow/commands/subcommands/deploy.py, src/tests/test_deploy.py
`deploy` was throwing a non-zero exit code because I returned the command as a message for testing purposes
This will only return the command if `--dry-run` is passed
=> Avoid a non-zero exit code on deploy subcommand

Pipfile, Pipfile.lock, compose/compose-flow.yml, setup.cfg, setup.py, src/compose_flow/commands/subcommands/base.py, src/compose_flow/commands/subcommands/deploy.py, src/compose_flow/commands/subcommands/env.py, src/compose_flow/commands/subcommands/profile.py, src/compose_flow/commands/subcommands/publish.py, src/compose_flow/commands/subcommands/remote.py, src/compose_flow/commands/subcommands/service.py, src/compose_flow/commands/subcommands/task.py, src/compose_flow/commands/workflow.py, src/compose_flow/config.py, src/compose_flow/docker_image.py, src/compose_flow/environment/backends/__init__.py, src/compose_flow/environment/backends/base_backend.py, src/compose_flow/environment/backends/swarm_backend.py, src/compose_flow/errors.py, src/compose_flow/kube/mixins.py, src/compose_flow/utils.py, src/tests/__init__.py, src/tests/test_backends.py, src/tests/test_env.py, src/tests/test_kube_mixins.py, src/tests/test_utils.py, src/tests/test_workflow.py
This is a sizable PR. It contains the following changes:
- support for overriding a custom config base name:
interface: https://github.com/openslate/compose-flow/pull/79/files#diff-4c6886de6fb0f1494eb05192ceab17d1R124
- support for interpolating `compose-flow.yml` and generating a new `compose-flow-<env>-<config-name>-config.yml` file that is used in place of the old, un-interpolated `compose-flow.yml`
core functionality: https://github.com/openslate/compose-flow/pull/79/files#diff-74e29ff7927b3648d3c7fc0a0bacaecbR93
- support for layering environments on top of each other
documented: https://github.com/openslate/compose-flow/pull/79/files#diff-0516e8fbe588e7299adbb064a6f40715R21
functionality: https://github.com/openslate/compose-flow/pull/79/files#diff-0516e8fbe588e7299adbb064a6f40715R40 …
=> Mono repo changes

.gitignore
Ignore `.eggs` directory so publish works again.
=> Ignore .eggs directory

Dockerfile
Contributes to https://openslate.myjetbrains.com/youtrack/issue/OS-2997
The main purpose of this PR was to upgrade `rancher` to get some nice bugdfixes, but we haven't upgraded `docker`, `kubectl`, `rancher` or `helm` in awhile - we should do so since things will break eventually
=> Upgrade CLI tools

Pipfile.lock, src/compose_flow/utils.py
This PR updates the `tag-version` release and the call so that the version format is compatible with Docker tags.  Certain symbols in the version string will cause Docker to crash (not the daemon entirely, but, for example, a `docker build` call.
=> New tag version
